name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install casaos
      run: curl -fsSL https://get.casaos.io
    - name: bash
      run: sudo bash
