name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest   # Mengubah runs-on menjadi ubuntu-latest untuk menggunakan Kali Linux

    steps:
    - name: Download
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip   # Mengubah perintah Invoke-WebRequest menjadi wget untuk Linux
    - name: Extract
      run: unzip ngrok.zip   # Mengubah Expand-Archive menjadi unzip untuk Linux
    - name: Ensure ngrok directory
      run: mv ngrok*/ ngrok   # Memastikan direktori ngrok telah diekstrak dengan benar
    - name: Auth
      run: ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN   # Mengubah .\ngrok\ngrok.exe menjadi ./ngrok/ngrok untuk Linux
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: sudo sysctl -w net.ipv4.ip_forward=1   # Mengubah perintah untuk mengaktifkan IP forwarding di Linux
    - run: sudo ufw allow 3389   # Mengubah perintah untuk mengizinkan port 3389 di firewall (gunakan perintah yang sesuai dengan firewall Kali Linux)
    - run: sudo systemctl start xrdp   # Mengubah perintah untuk memulai layanan RDP di Linux
    - run: sudo passwd runneradmin   # Mengubah perintah untuk mengatur kata sandi pengguna di Linux
    - name: Create Tunnel
      run: ./ngrok/ngrok tcp 3389   # Mengubah perintah untuk membuat tunnel TCP di Linux
