name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest   # Change runs-on to ubuntu-latest for Kali Linux

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip   # Download ngrok using wget
    - name: Extract ngrok
      run: unzip ngrok.zip   # Extract ngrok using unzip
    - name: Check and move ngrok directory
      run: ls -d ngrok*/ || exit 1 && mv ngrok*/ ngrok   # Check and move ngrok directory
    - name: Set authentication token
      run: ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN   # Set ngrok authentication token
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable IP forwarding
      run: sudo sysctl -w net.ipv4.ip_forward=1   # Enable IP forwarding
    - name: Allow port 3389 in firewall
      run: sudo ufw allow 3389   # Allow port 3389 in firewall
    - name: Start RDP service
      run: sudo systemctl start xrdp   # Start RDP service
    - name: Set user password
      run: echo 'runneradmin:P@ssw0rd!' | sudo chpasswd   # Set user password
    - name: Create ngrok tunnel
      run: ./ngrok/ngrok tcp 3389   # Create ngrok TCP tunnel on port 3389
