name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable Virtual Machine Platform and WSL
      run: |
        dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
        dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
        wsl --set-default-version 2
    - name: Download Docker Desktop Installer
      run: Invoke-WebRequest -Uri "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe" -OutFile "DockerDesktopInstaller.exe"
    - name: Install Docker Desktop
      run: .\DockerDesktopInstaller.exe /quiet /norestart
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip
    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken "$Env:NGROK_AUTH_TOKEN"
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
    - name: Enable Remote Desktop Firewall Rule
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Enable Remote Desktop User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
    - name: Set Local User Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Download Ubuntu image
      run: Invoke-WebRequest -Uri "https://aka.ms/wslubuntu2004" -OutFile "ubuntu2004.tar.gz"
    - name: Extract Ubuntu image
      run: Expand-Archive ubuntu2004.tar.gz -DestinationPath Ubuntu
    - name: Import Ubuntu image to WSL
      run: wsl --import Ubuntu C:\WSL\Ubuntu Ubuntu --version 2
    - name: Start Ubuntu in WSL
      run: wsl -d Ubuntu
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
